service: schedule-pdp-bot

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  lambdaHashingVersion: 20201221
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  webhook:
    handler: src/handler.webhook
    events:
      - http:
          path: /
          method: post

useDotenv : true